-- 创建数据库
CREATE DATABASE IF NOT EXISTS resume_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE resume_db;

-- 管理员表
CREATE TABLE IF NOT EXISTS admin (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='管理员表';

-- 简历表
CREATE TABLE IF NOT EXISTS resume (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL COMMENT '用户名',
    work_years INT NOT NULL DEFAULT 0 COMMENT '工作年限',
    age INT NOT NULL DEFAULT 0 COMMENT '年龄',
    gender VARCHAR(10) NOT NULL DEFAULT '' COMMENT '性别',
    resume_content TEXT COMMENT '简历内容（纯文本）',
    file_data MEDIUMBLOB COMMENT '原始PDF文件',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='简历表';

-- 已有数据库迁移（如列不存在会报错，可忽略）
ALTER TABLE resume ADD COLUMN IF NOT EXISTS gender VARCHAR(10) NOT NULL DEFAULT '' COMMENT '性别' AFTER age;
ALTER TABLE resume ADD COLUMN IF NOT EXISTS file_data MEDIUMBLOB COMMENT '原始PDF文件' AFTER resume_content;

